---
# Manifest file downloaded from fusion
externalId: tr-create_asset_hierarchy
name: create_asset_hierarchys
query:
    file: transformation.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
dataSetExternalId: src:001:sap:ds
# Added authentication information
authentication:
    clientId: 63386619-90c1-4a63-ac6d-47b5968b3d8f
    clientSecret: 10I8Q~VqSSU~flJWu0129AB-I_8nTMw0haBOZdvz
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
    cdfProjectName: cdf-bootcamp-31-test
    scopes:
        - https://westeurope-1.cognitedata.com/.default
